### ISSUE TITLE
Will this be open source?

### ISSUE THREAD

**Issue by wisingman** [A4Papers/Chat-Filter#1]
I'm just wondering because there should either be a way to disable viewing alerts entirely although having it open source would also be nice

**Comment by A4Papers** [comment]
Hi, You can negate the permission 'chatfilter.view' and that will basically disable any ingame notifications however I do agree that disabling via a configuration option is a good idea.
As for the source I've been planing on putting it up here, Feel free to add me on discord to discuss (A4Papers#3211)
